### ISSUE TITLE
Add install script for Linux

### ISSUE THREAD

**Issue by ethmtrgt** [ethmtrgt/pydw#2]
Create an installation script to run the program directly on terminal.

**Comment by prasannassp** [comment]
Hi @ethmtrgt 
I have added the installation script and thereby cleared the issue. Please review it and merge to the main branch.
Thanks in advance.

**Comment by ethmtrgt** [comment]
Hello @prasannassp 
Actually I've reviewed and requested a change about a week ago. You probably missed that. 
But that's not a problem, I will merge. Thank you for your contribution :slightly_smiling_face:.
