### ISSUE TITLE
Make the directory optional

### ISSUE THREAD

**Issue by ethmtrgt** [ethmtrgt/pydw#7]
Actually it is not useful to specify the directory in every single command. It can be more useful if it's optional. So `-d` argument must be made an option and if it wasn't specified, it should use the current directory.

For example;
`pydw --l input.txt` instead `pydw -l input.txt -d output/files/`

**Comment by paulafrederick** [comment]
Can I work on this?

**Comment by ethmtrgt** [comment]
@paulafrederick Yes of course.
